name: Branch Protection

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Обязательная проверка для защиты main ветки
  required-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python from .python-version
        run: uv python install

      - name: Install dependencies
        run: |
          uv sync --dev
          uv add --dev ruff mypy

      - name: Run ruff linter (fail on error)
        run: uv run ruff check . --output-format=github

      - name: Run ruff formatter check (fail on error)
        run: uv run ruff format --check . --diff

      - name: Run mypy type checker (fail on error)
        run: uv run mypy --strict src/ --show-error-codes

      - name: All checks passed
        run: echo "✅ All linting and formatting checks passed!"
